---
title: 'Homework #3'
author: "Vincent Tam"
date: "October 9, 2018"
output:
  github_document: default
---
```{r Library Package Setup and Global Options, echo = FALSE}
## Prepare Setup to Answer Problem 3
## Install Libraries
library(tidyverse)
library(ggplot2)
library(forcats)
library(knitr)
library(ggridges)
library(janitor)
## install.packages("devtools") Already Installed but do not want to do it constantly
## Upload Datasets
library(p8105.datasets)
data(brfss_smart2010)
```
Problem 1 - Behavioral Risk Factors Surveillance System (BRFSS) Data
```{r Clean and Format Data to Prepare for Answering Questions}
## Clean, Filter, Select, Mutate, and Separate Variables
brfss_data = 
  brfss_smart2010 %>%
## format the data to use appropriate variable names
  janitor::clean_names() %>%
## focus on the “Overall Health” topic
  filter(topic == "Overall Health") %>%
## include only responses from “Excellent” to “Poor”
  filter(response == "Excellent" | response == "Very good" | response == "Good" | response == "Fair" | response == "Poor") %>%
## organize responses as a factor taking levels ordered from “Excellent” to “Poor”
  mutate(cleaned_response = as.factor(response)) %>%
  ## organize and select relevant columns for questions
  select(year, locationdesc, topic, response, data_value) %>%
  separate(locationdesc, into = c("state", "county"), sep = " - ")
brfss_data
```
Answers to Homework Questions
```{r Answering Questions}
brfss_data_2002 =
  filter(brfss_data, year == "2002") %>%
  distinct(state, county) %>%
  count(state) %>%
  filter(n == 7)
## In 2002, which states were observed at 7 locations?
"In 2002, the following states had 7 locations:" 
brfss_data_2002
```
```{r Spaghetti Plotting}
## Spaghetti Plots
brfss_plot = 
  brfss_data %>%
  distinct(year, state, county) %>%
  select(year, state, county) %>%
  group_by(year, state) %>%
  mutate(count = n())
"Spaghetti Plot showing the number of locations in each state from 2002 to 2010."
ggplot(brfss_plot, aes(x = year, y = count, color = state)) + geom_point() + geom_line()
```

## Making Table
```{r Table Making}
brfss_table =   
  brfss_data %>%
  filter(year == '2002' | year == '2006' | year == '2010') %>%
  filter(state == 'NY') %>%
  filter(response == 'Excellent') %>%
  mutate(data_value_numeric = as.numeric(data_value)) %>%
  group_by(year) %>%
  summarize(brfss_NYexcellentsd = sd(data_value_numeric), brfss_NYexcellentmean = mean(data_value_numeric))
brfss_table
```
```{r Average Proportions, warning = FALSE}
brfss_proportions = 
  brfss_data %>%
  group_by(year, state, response) %>%
  summarize(brfss_excellentmean = mean(as.numeric(data_value)), 
            brfss_verygoodmean = mean(as.numeric(data_value)), 
            brfss_goodmean = mean(as.numeric(data_value)),
            brfss_fairmean = mean(as.numeric(data_value)),
            brfss_poormean = mean(as.numeric(data_value))) %>%
  gather(key = cleaned_response, value = proportion, brfss_excellentmean:brfss_poormean) %>% 
  mutate(response = forcats::fct_relevel(response, c("Poor", "Fair", "Good", "Very good", "Excellent"))) 
ggplot(brfss_proportions, aes(x = year, y = proportion, fill = response)) + geom_violin() + facet_grid(~response) + theme(axis.text.x = element_text(angle = 90)) + labs(title = "Average Proportion per Response Category"  )
brfss_proportions
```
## Problem #2
```{r}
## install.packages("devtools")
## devtools::install_github("p8105/p8105.datasets"); already installed but do not want to install every time
##library(p8105.datasets); already installed but do not want to install every time
library(tidyverse)
data(instacart)
```
```{r Problem 2, eval = FALSE}
instacart_cleaned =
  instacart %>%
  janitor::clean_names() 
length(unique(instacart_cleaned$aisle)) 
```
```{r Problem 2 Most Common, eval = FALSE}
most_ordered =
  instacart_cleaned %>%
  group_by(aisle_id) %>%
  summarize(n = n()) %>%
  filter(min_rank(desc(n))<6)
most_ordered
```
most_ordered %>%
  group_by(aisle_id, n) %>%
  mutate(temp_ranking = min_rank(most_ordered))
```{r Make a plot that shows the number of items ordered in each aisle. Order aisles sensibly, and organize your plot so others can read it.}
## most_ordered %>%
##  mutate(aisle_idnumeric = as.factor(aisle_id)) %>%
##  mutate(aisle_idnumeric = forcats::fct_reorder(aisle_id_numeric, n)) %>%
##  ggplot(most_ordered, aes(x = aisle_idnumeric) + geom_bar(stat = "identity") + scale_x_discrete(drop = FALSE))
```
## Problem #3
```{r}
data(ny_noaa)
```
```{r}
nynoaa_cleaned = 
  ny_noaa %>% 
  janitor::clean_names() %>%
  separate(date, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(tmin = as.numeric(tmin)/10, tmax = as.numeric(tmax)/10)
```
```{r}
nynoaa_snow = 
  nynoaa_cleaned %>%
  group_by(snow) %>%
  summarize(n = n()) %>%
  top_n(3)
nynoaa_snow
```
```{r}
maxtempJanJul_plot =
  nynoaa_cleaned %>%
  na.omit() %>%
  select(year, month, id, tmin, tmax) %>%
  filter(month == "01" | month == "07") %>%
    group_by(year, month, id) %>%
  summarize(tmax_mean = mean(tmax)) %>%
  ggplot(aes(x = year, y = tmax_mean)) + geom_boxplot() + facet_grid(.~month) + theme(axis.text.x = element_text(size = 9, angle = 90)) + labs(title = "Comparison of Average Max Temps in Celcius between January and July from 1981 to 2010", x = "Years", y = "Temperature (Celcius)" )
maxtempJanJul_plot
```
```{r}
plot1_minmax =
  nynoaa_cleaned %>%
  na.omit() %>%
  select(tmin, tmax) %>%
  ggplot(aes(x = tmin, y = tmax )) + geom_hex() + labs(title = "Minimum Temperatures vs Maximum Temperatures", x = "Minimum Temp", y = "Maximum Temp") + theme(axis.text.x = element_text(size = 9, angle = 90))
plot1_minmax
```
```{r}
plot2_snowfall =
  nynoaa_cleaned %>%
  na.omit() %>%
  filter(snow > 0 & snow < 100) %>%
  ggplot(aes(x = year, y = snow )) + geom_boxplot() + labs(title = "Distribution of Snowfall Values by Years", x = "Year", y = "Snowfall Valuesp") + theme(axis.text.x = element_text(size = 9, angle = 90))
plot2_snowfall
```